title: norrisaftcc's homepage
description: GitHub Pages example for Dataman
github_username: norrisaftcc
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
